<a href="https://colab.research.google.com/github/BARURISAIAVINASH/AVINASH_datascience/blob/main/Python_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists

A   = [[1 ,2],
      [3, 4]]
B   = [[1 ,2 ,3 ,4 ,5],
      [5, 6 ,7 ,8 ,9]]
    
def matrix_mul(A, B): 
  if len(A[0])==len(B):
  
  
  
    result = [[0 for x in range(len(B[0]))] for y in range(len(A))]  
    if len(A[0])==len(B):
      for i in range(len(A)): 
        for j in range(len(B[0])): 
          for k in range(len(B)): 
            result[i][j] += A[i][k] * B[k][j] 
  
      return result

    else:
      print( 'Not Possible')

matrix_mul(A, B)
    


[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]

In [ ]:
A   = [[1 ,3, 4],
             [2, 5 ,7],
             [5 ,9, 6]]
B   = [[1, 0 ,0],
             [0 ,1 ,0],
             [0 ,0 ,1]]

def matrix_mul(A, B): 
  if len(A[0])==len(B):
  
  
  
    result = [[0 for x in range(len(B[0]))] for y in range(len(A))]  
    if len(A[0])==len(B):
      for i in range(len(A)): 
        for j in range(len(B[0])): 
          for k in range(len(B)): 
            result[i][j] += A[i][k] * B[k][j] 
  
      return result

    else:
      print( 'Notpossible')

matrix_mul(A, B)
 

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]

In [ ]:

A   = [[1 ,2],
             [3, 4]]
B   = [[1, 4],
             [5 ,6],
             [7 ,8],
             [9, 6]]








def matrix_mul(A, B): 
  if len(A[0])==len(B):
  
  
  
    result = [[0 for x in range(len(B[0]))] for y in range(len(A))]  
    if len(A[0])==len(B):
      for i in range(len(A)): 
        for j in range(len(B[0])): 
          for k in range(len(B)): 
            result[i][j] += A[i][k] * B[k][j] 
  
      return result

  else:
    print( 'Notpossible')

matrix_mul(A, B)
 

Notpossible


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    #.
    #.
    #.
    return #selected_random_number

def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued()

In [ ]:
from random import uniform
import random
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    #sort_list=A.sort()
    sum_A=0
    global prob_A
    prob_A=[]
    for i in range(len(A)):
      sum_A=sum_A+A[i]
    for j in range(len(A)):
      prob_A.append(A[j]/sum_A)
    
    #max_prob=max(prob_A)
    #print(sum_A)
    #print(prob_A)
    #print(max_prob)
    return (A[prob_A.index(max(prob_A))])
    
    #.
    #.
    #return A[A.index(max(prob_A))] #selected_random_number

def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)
#A = [0, 5 ,27, 6 ,13 ,28, 100 ,45, 10, 79]
A= random.sample(range(10, 30), 5)
print(A)


sampling_based_on_magnitued()

[13, 20, 21, 28, 10]
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28
28


In [ ]:
A = [0, 5 ,27, 6 ,13 ,28, 100 ,45, 10, 79]

sum=0
for i in A:
    sum+=i
y=0
l=[]
for i in A:
    l.append(i/sum)
print(l)
c= [None] * len(l)
print(c)
c[0]=0
for k in range(1,len(A)):
  c[k] = c[k-1] + l[k]
print(c)
import random 
from random import uniform
r = random.uniform(0.0,1.0)
print(r)
for k in range(len(c)):
  if r<=c[k]:
    print(c[k])
    


    

[0.0, 0.01597444089456869, 0.08626198083067092, 0.019169329073482427, 0.04153354632587859, 0.08945686900958466, 0.3194888178913738, 0.14376996805111822, 0.03194888178913738, 0.2523961661341853]
[None, None, None, None, None, None, None, None, None, None]
[0, 0.01597444089456869, 0.10223642172523961, 0.12140575079872204, 0.16293929712460065, 0.2523961661341853, 0.5718849840255591, 0.7156549520766773, 0.7476038338658146, 1.0]
0.5000021529848795
0.5718849840255591
0.7156549520766773
0.7476038338658146
1.0


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(s):
    # write your code
    # import re



    m=re.sub("\D","",s)
    #print(m)
    n=re.sub("\d","#",m)
    return(n) # modified string which is after replacing the # with digits
s='234'
replace_digits(s)

'###'

In [ ]:
import re
def replace_digits(s):
  m=re.sub("\D","",s)
  #print(m)
  n=re.sub("\d","#",m)
  print(n)
s='a2b3c4 '
replace_digits(s)

###


In [ ]:
import re
def replace_digits(s):
  m=re.sub("\D","",s)
  #print(m)
  n=re.sub("\d","#",m)
  return n
s='abc'
replace_digits(s)

''

In [ ]:
import re
def replace_digits(s):
  m=re.sub("\D","",s)
  
  n=re.sub("\d","#",m)
  return n
s='#2a$#b%c%561#  '
replace_digits(s)

'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a=sorted(Marks)
#a=Marks.sort()
for i in range(5):
  b=a[i]
  k=Marks.index(b)
  print('{} {}'.format(Students[k],Marks[k]))

student3 12
student4 14
student9 35
student6 43
student1 45


In [ ]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a=sorted(Marks)
#a=Marks.sort()
for i in range(9,4,-1):
  b=a[i]
  k=Marks.index(b)
  print('{} {}'.format(Students[k],Marks[k]))

student8 98
student10 80
student2 78
student5 48
student7 47


In [ ]:
marks=[]
for i in Marks:
  if i>25 and i<75:
    marks.append(i)
#print(marks)
a=sorted(marks)
for i in range(len(marks)):
  b=a[i]
  k=Marks.index(b)
  
  print('{} {}'.format(Students[k],a[i]))

student9 35
student6 43
student1 45
student7 47
student5 48


In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    # write code for computing top top 5 students
    
    top_5_students = # compute this
    # write code for computing top least 5 students
    least_5_students = # compute this
    # write code for computing top least 5 students
    students_within_25_and_75 = # compute this
    
    return top_5_students, least_5_students, students_within_25_and_75
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print(# those values)

<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    c=[]
    for i ,j in S:
      n1=P[0]*i
      n2=P[1]*j
      n=n1+n2
      d1=math.sqrt(i*i+j*j)
      d2=math.sqrt(P[0]*P[0]+P[1]*P[1])
      d=d1*d2
      c.append(math.acos(n/d))
    #print(c)
    a=sorted(c)
    for i in range(5):
      
      k=c.index(a[i])
      print( "{}".format(S[k]))
      
    
    

   
   

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
#print(points) #print the returned values

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


In [ ]:
 y = [S for S in sorted(zip(S,c), key=lambda i:i[1])]
    a=[]
    count=0
    while count<5:
      a.append(y[count][0])
      count+=1
    return a



    return closest_points_to_p  # its list of tuples

<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
##https://stackoverflow.com/questions/57188227/to-find-whether-a-given-line-equation-is-able-to-separate-the-two-lists-of-poi


import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your 
    c=[]
    d=[]
    e=0
    for i in Red:
      
      a=line.replace('x','*'+str(i[0]))
      a=a.replace('y','*'+str(i [1]))
      
      a=eval(a)
      c.append(a)
      
    for j in Blue:
      b=line.replace('x','*'+str(j[0]))
      b=b.replace('y','*'+str(j[1]))
     
      b=eval(b)
      d.append(b)
    
    for i in c:
      for j in d:
        if i>0 and j<0:
          
          e=e+1
        elif i<0 and j>0:
          e=e-1
        else:
          break
    if e==len(c)**2 or e==-len(c)**2:
     return 'YES'
    else:
      return 'NO'
    
   

      




      
    #return #yes/no

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [ ]:


# Test cases
tests = [
    "_,_,_,24",
    "40,_,_,_,60",
    "80,_,_,_,_",
     "_,_,30,_,_,_,50,_,_"]

for i in tests:
    x = i.split(",")
    print(x)
    c=[]
    z=0
    if x[0]=='_':
      c=[]
      for i in x:
        if i!='_':
          c.append(i)
      z=z+1
      
    if x[len(x)-1]=='_':
      c=[]
      for i in x:
        if i!="_":
          c.append(i)
      z=z+1
    if x[0]!="_" and x[len(x)-1]!="_":
      c=[]
      for i in x:
        if i!="_":
          c.append(i)
      z=z+1
    
    sum=0
    y=[]
    if z==1:
      for i in c:
        sum=sum+int(i)
        s=sum/len(x)
      for j in range(len(x)):
        y.append(s)
    #print(y)
    if z==2:
      y=[]
      for i in range(len(c)):
        if i==0:
          q=x.index(c[i])

          p=int(c[i])/(q+1)
          for i in range(q):
            y.append(p)
        
        else:
          w=x.index(c[i])
          e=w-q+1
          p=(int(c[i])+y[0])/e
          for i in range(q,w+1):
            y.append(p)
    
      if len(y)!=len(x):
        p=len(x)-len(y)
        q=y[-1]/(p+1)
        y.pop()
        for i in range(p+1):
          y.append(q)
    print(y)








      

      
      


    
      

   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
   

['_', '_', '_', '24']
[6.0, 6.0, 6.0, 6.0]
['40', '_', '_', '_', '60']
[20.0, 20.0, 20.0, 20.0, 20.0]
['80', '_', '_', '_', '_']
[16.0, 16.0, 16.0, 16.0, 16.0]
['_', '_', '30', '_', '_', '_', '50', '_', '_']
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


In [ ]:
def fun(x, a, b):
    if a == -1:
        v = float(x[b])/(b+1)
        for i in range(a+1,b+1):
            x[i] = v
    elif b == -1:
        v = float(x[a])/(len(x)-a)
        for i in range(a, len(x)):
            x[i] = v
    else:
        v = (float(x[a])+float(x[b]))/(b-a+1)
        for i in range(a,b+1):
            x[i] = v
    return x

def r(t):
    
    x = t.replace(" ","").split(",")
    #print(x)
    
    y = [i for i, v in enumerate(x) if v != '_']
    print(y)
    print(x)
    
    if y[0] != 0:
        y = [-1] + y
        print(y)
    
    if y[-1] != len(x)-1:
        y = y + [-1] 
        print(y)   
    
    for (a, b) in zip(y[:-1], y[1:]): 
        print(a)
        print(b)
        fun(x,a,b)          
    return x


t= ["_,_,_,24","40,_,_,_,60","80,_,_,_,_", "_,_,30,_,_,_,50,_,_"]

for i in t:
    print (r(i))

[3]
['_', '_', '_', '24']
[-1, 3]
-1
3
[6.0, 6.0, 6.0, 6.0]
[0, 4]
['40', '_', '_', '_', '60']
0
4
[20.0, 20.0, 20.0, 20.0, 20.0]
[0]
['80', '_', '_', '_', '_']
[0, -1]
0
-1
[16.0, 16.0, 16.0, 16.0, 16.0]
[2, 6]
['_', '_', '30', '_', '_', '_', '50', '_', '_']
[-1, 2, 6]
[-1, 2, 6, -1]
-1
2
2
6
6
-1
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
  
    # your code
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

In [ ]:
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]


for k in ['F1', 'F2', 'F3', 'F4', 'F5']:
    for m in ['S1', 'S2', 'S3']:
        #values(k,m)
        n=0
        p=0
        for i in range(len(A)):
          if(A[i][1]==m):
            p=p+1
            if (A[i][0]==k):
              n=n+1
        

           
        print('P(F={}|S=={})='.format(k,m),(n/p))



P(F=F1|S==S1)= 0.25
P(F=F1|S==S2)= 0.3333333333333333
P(F=F1|S==S3)= 0.0
P(F=F2|S==S1)= 0.25
P(F=F2|S==S2)= 0.3333333333333333
P(F=F2|S==S3)= 0.3333333333333333
P(F=F3|S==S1)= 0.0
P(F=F3|S==S2)= 0.3333333333333333
P(F=F3|S==S3)= 0.3333333333333333
P(F=F4|S==S1)= 0.25
P(F=F4|S==S2)= 0.0
P(F=F4|S==S3)= 0.3333333333333333
P(F=F5|S==S1)= 0.25
P(F=F5|S==S2)= 0.0
P(F=F5|S==S3)= 0.0


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
   
  S1 = S1.split() 
  S2 = S2.split() 
  a=[]
  b=[]
  c=[]
  for i in S1: 
    if i  not in S2: 
      b.append(i)
  for j in S2: 
    if j  not in S1: 
      a.append(j)
  for i in S1:
    if i in S2:
      c.append(i)
  
  print(len(c))
  print(b)
  print(a)
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
string_features(S1, S2)


7
['first', 'F', '5']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math
# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    
  n=len(A)  
  loss=0
  for i in A :
    loss=loss+(i[0])*(math.log10(i[1]))+((1-i[0])*(math.log10(1-i[1])))
    
  loss=(-1/n)*loss
  return loss


A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
n=len(A)
lo = compute_log_loss(A)
print(lo)

0.42430993457031635
